name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      PHP_VERSION: 8.2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go ${{ env.PHP_VERSION }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: install dependencies
        run: composer install
      
      - name: Build
        run: composer test-all

      - name: Test
        run: composer lint-code
